# Generated by Django 2.2.2 on 2020-05-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appvuln',
            fields=[
                ('vuln_name', models.CharField(max_length=15, verbose_name='漏洞名称')),
                ('vuln_url', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='漏洞地址')),
                ('vuln_detail', models.TextField()),
                ('vuln_level', models.IntegerField(choices=[(1, '低危'), (2, '中危'), (3, '高危'), (4, '严重')], default='', verbose_name='漏洞等级')),
                ('vuln_process', models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '处理完成')], default=1, verbose_name='状态')),
                ('result', models.IntegerField(choices=[(1, '已修复'), (2, '已忽略')], verbose_name='处理结果')),
                ('vuln_handler', models.CharField(blank=True, max_length=15, null=True, verbose_name='漏洞经办人')),
                ('handler_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='经办人电话')),
                ('detect_time', models.DateTimeField(verbose_name='发现时间')),
                ('done_time', models.DateTimeField(verbose_name='处理完成时间')),
            ],
            options={
                'verbose_name': '应用程序漏洞',
                'verbose_name_plural': '应用程序漏洞',
            },
        ),
        migrations.CreateModel(
            name='Systemvuln',
            fields=[
                ('ipaddress', models.ForeignKey(db_column='ipaddress', default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asset.Machine')),
                ('vuln_name', models.CharField(max_length=15, verbose_name='漏洞名称')),
                ('vuln_detail', models.TextField()),
                ('vuln_level', models.IntegerField(choices=[(1, '低危'), (2, '中危'), (3, '高危'), (4, '严重')], verbose_name='漏洞等级')),
                ('vuln_process', models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '处理完成')], default=1, verbose_name='处理进度')),
                ('result', models.IntegerField(choices=[(1, '已修复'), (2, '已忽略'), (3, '已关机')], verbose_name='处理结果')),
                ('vuln_handler', models.CharField(blank=True, max_length=15, null=True, verbose_name='漏洞经办人')),
                ('handler_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='经办人电话')),
                ('detect_time', models.DateTimeField(verbose_name='发现时间')),
                ('done_time', models.DateTimeField(verbose_name='处理完成时间')),
            ],
            options={
                'verbose_name': '系统漏洞',
                'verbose_name_plural': '系统漏洞',
            },
        ),
    ]
