# Generated by Django 2.2.2 on 2020-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvuln',
            name='result',
            field=models.IntegerField(blank=True, choices=[(1, '已修复'), (2, '已忽略')], null=True, verbose_name='处理结果'),
        ),
    ]
