# Generated by Django 2.2.2 on 2020-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0003_auto_20200522_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemvuln',
            name='result',
            field=models.IntegerField(blank=True, choices=[(1, '已修复'), (2, '已忽略'), (3, '已关机')], null=True, verbose_name='处理结果'),
        ),
    ]
