# Generated by Django 2.2.2 on 2020-05-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='域名')),
                ('project', models.CharField(blank=True, max_length=250, null=True, verbose_name='项目名称')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目联系人')),
                ('owner_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系人电话')),
                ('level', models.IntegerField(choices=[(1, '非常重要'), (2, '重要'), (3, '一般'), (4, '不重要')], default=2, verbose_name='业务重要性')),
            ],
            options={
                'verbose_name': '域名列表',
                'verbose_name_plural': '域名列表',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('ipaddress', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='IP地址')),
                ('project', models.CharField(blank=True, max_length=250, null=True, verbose_name='项目名称')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='资产联系人')),
                ('owner_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系人电话')),
                ('level', models.IntegerField(choices=[(1, '非常重要'), (2, '重要'), (3, '一般'), (4, '不重要')], default=2, verbose_name='资产重要性')),
            ],
            options={
                'verbose_name': '机器列表',
                'verbose_name_plural': '机器列表',
            },
        ),
    ]
